name:                aoc2020
version:             0.1.0.0
github:              "tbreslein/aoc2020"
license:             MIT
author:              "Tommy Breslein"
maintainer:          "tommy.breslein@protonmail.com"
copyright:           "2020 Tommy Breslein"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: My solutions for Advent of Code 2020

dependencies:
- base >= 4.7 && < 5
- split
- cond
- text
- raw-strings-qq

library:
  source-dirs: src

executables:
  aoc2020-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2020

tests:
  aoc2020-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2020
    - hspec
    - QuickCheck
    - raw-strings-qq
